name: job

on:
  pull_request:
    branches: [ main ]

jobs:
  # unit test를 실행한다
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ../ci_test